<?php

namespace App\Filament\Admin\Resources\BookResource\Pages;

use App\Filament\Admin\Resources\BookResource;
use App\Models\Book;
use Filament\Resources\Pages\CreateRecord;

class CreateBook extends CreateRecord
{
    protected static string $resource = BookResource::class;

    protected function getHeaderActions(): array
    {
        return [

        ];
    }

    protected function mutateFormDataBeforeCreate(array $data): array
    {
//        dd($data);
//        $data['order'] = $data['order'] ?? 0;
        return parent::mutateFormDataBeforeCreate($data); // TODO: Change the autogenerated stub
    }

    public function afterCreate(array $data, Book $book): void
    {

    }
}
